name: "Docker Run"
description: "Performs Docker Run commands with dynamic environment variables"
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  image:
    description: "Name of the Docker image to run"
    required: true
  env_variables:
    description: "JSON object with dynamic environment variables"
    required: false
outputs:
  MESSAGE:
    description: "Output of docker run command"