name: "Docker Run"
description: "Performs Docker Run commands with dynamic environment variables"
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  image_name:
    description: "Name of the Docker image to run"
    required: true
outputs:
  MESSAGE:
    description: "Output of docker run command"